name: longzhuzhu-nianyu
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: longzhuzhu-nianyu-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync longzhuzhu-nianyu-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/longzhuzhu/nianyu.git"
          source_branch: "main"
          destination_branch: "longzhuzhu-nianyu"
          github_token: ${{ secrets.PAT }}
